"""initial unified schema (sqlite->pg shared)

Revision ID: 86a96f7d21f6
Revises: 
Create Date: 2026-09-05 13:44:55.132163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a96f7d21f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_broadcast_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('audience_free', sa.Boolean(), nullable=True),
    sa.Column('audience_premium', sa.Boolean(), nullable=True),
    sa.Column('channel_telegram', sa.Boolean(), nullable=True),
    sa.Column('channel_app', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('telegram_pending', sa.Integer(), nullable=True),
    sa.Column('telegram_sent', sa.Integer(), nullable=True),
    sa.Column('telegram_failed', sa.Integer(), nullable=True),
    sa.Column('app_pending', sa.Integer(), nullable=True),
    sa.Column('app_read', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_broadcast_messages_id'), 'app_broadcast_messages', ['id'], unique=False)
    op.create_table('app_pending_telegram_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('telegram_name', sa.String(length=255), nullable=True),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_pending_telegram_auth_code'), 'app_pending_telegram_auth', ['code'], unique=True)
    op.create_index(op.f('ix_app_pending_telegram_auth_id'), 'app_pending_telegram_auth', ['id'], unique=False)
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('daily_asana_enabled', sa.Boolean(), nullable=True),
    sa.Column('daily_asana_time', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('last_daily_asana_date', sa.Date(), nullable=True),
    sa.Column('total_practices', sa.Integer(), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=True),
    sa.Column('total_practice_minutes', sa.Integer(), nullable=True),
    sa.Column('total_practice_days', sa.Integer(), nullable=True),
    sa.Column('last_practice_at', sa.DateTime(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_users_email'), 'app_users', ['email'], unique=True)
    op.create_index(op.f('ix_app_users_id'), 'app_users', ['id'], unique=False)
    op.create_index(op.f('ix_app_users_telegram_id'), 'app_users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_app_users_username'), 'app_users', ['username'], unique=True)
    op.create_table('app_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=500), nullable=False),
    sa.Column('video_type', sa.String(length=20), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('asana_id', sa.Integer(), nullable=True),
    sa.Column('asana_name', sa.String(length=255), nullable=True),
    sa.Column('sequence_name', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_videos_id'), 'app_videos', ['id'], unique=False)
    op.create_table('asana_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asana_name', sa.String(length=200), nullable=False),
    sa.Column('video_path', sa.String(length=500), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructor_name', sa.String(length=100), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('focus_points', sa.String(length=500), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asana_videos_asana_name'), 'asana_videos', ['asana_name'], unique=False)
    op.create_index(op.f('ix_asana_videos_id'), 'asana_videos', ['id'], unique=False)
    op.create_table('ready_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('video_path', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('focus_areas', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('instructor_name', sa.String(length=255), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ready_sequences_id'), 'ready_sequences', ['id'], unique=False)
    op.create_table('app_broadcast_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['app_broadcast_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_broadcast_deliveries_id'), 'app_broadcast_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_app_broadcast_deliveries_message_id'), 'app_broadcast_deliveries', ['message_id'], unique=False)
    op.create_index(op.f('ix_app_broadcast_deliveries_user_id'), 'app_broadcast_deliveries', ['user_id'], unique=False)
    op.create_table('app_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asana_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_favorites_id'), 'app_favorites', ['id'], unique=False)
    op.create_table('app_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('contact', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('premium_days', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('admin_sent', sa.Boolean(), nullable=True),
    sa.Column('client_seen', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_payments_id'), 'app_payments', ['id'], unique=False)
    op.create_table('app_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asanas', sa.JSON(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_sequences_id'), 'app_sequences', ['id'], unique=False)
    op.create_table('app_user_avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_avatars_id'), 'app_user_avatars', ['id'], unique=False)
    op.create_table('app_user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('subscription_type', sa.String(length=20), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=True),
    sa.Column('subscription_start', sa.DateTime(), nullable=True),
    sa.Column('subscription_end', sa.DateTime(), nullable=True),
    sa.Column('trial_used', sa.Boolean(), nullable=True),
    sa.Column('trial_start', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('daily_generations_used', sa.Integer(), nullable=True),
    sa.Column('last_generation_date', sa.Date(), nullable=True),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('payment_provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_app_user_subscriptions_id'), 'app_user_subscriptions', ['id'], unique=False)
    op.create_table('app_practice_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('asanas_practiced', sa.JSON(), nullable=True),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('asana_durations', sa.JSON(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sequence_id'], ['app_sequences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_practice_sessions_id'), 'app_practice_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_practice_sessions_id'), table_name='app_practice_sessions')
    op.drop_table('app_practice_sessions')
    op.drop_index(op.f('ix_app_user_subscriptions_id'), table_name='app_user_subscriptions')
    op.drop_table('app_user_subscriptions')
    op.drop_index(op.f('ix_app_user_avatars_id'), table_name='app_user_avatars')
    op.drop_table('app_user_avatars')
    op.drop_index(op.f('ix_app_sequences_id'), table_name='app_sequences')
    op.drop_table('app_sequences')
    op.drop_index(op.f('ix_app_payments_id'), table_name='app_payments')
    op.drop_table('app_payments')
    op.drop_index(op.f('ix_app_favorites_id'), table_name='app_favorites')
    op.drop_table('app_favorites')
    op.drop_index(op.f('ix_app_broadcast_deliveries_user_id'), table_name='app_broadcast_deliveries')
    op.drop_index(op.f('ix_app_broadcast_deliveries_message_id'), table_name='app_broadcast_deliveries')
    op.drop_index(op.f('ix_app_broadcast_deliveries_id'), table_name='app_broadcast_deliveries')
    op.drop_table('app_broadcast_deliveries')
    op.drop_index(op.f('ix_ready_sequences_id'), table_name='ready_sequences')
    op.drop_table('ready_sequences')
    op.drop_index(op.f('ix_asana_videos_id'), table_name='asana_videos')
    op.drop_index(op.f('ix_asana_videos_asana_name'), table_name='asana_videos')
    op.drop_table('asana_videos')
    op.drop_index(op.f('ix_app_videos_id'), table_name='app_videos')
    op.drop_table('app_videos')
    op.drop_index(op.f('ix_app_users_username'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_telegram_id'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_id'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_email'), table_name='app_users')
    op.drop_table('app_users')
    op.drop_index(op.f('ix_app_pending_telegram_auth_id'), table_name='app_pending_telegram_auth')
    op.drop_index(op.f('ix_app_pending_telegram_auth_code'), table_name='app_pending_telegram_auth')
    op.drop_table('app_pending_telegram_auth')
    op.drop_index(op.f('ix_app_broadcast_messages_id'), table_name='app_broadcast_messages')
    op.drop_table('app_broadcast_messages')
    # ### end Alembic commands ###